# Generated by Django 4.1.5 on 2023-01-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kiet", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rollnumber", models.CharField(max_length=10)),
                ("password", models.CharField(max_length=255)),
            ],
        ),
    ]
