# Generated by Django 4.1.5 on 2023-01-20 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kiet", "0002_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mymodel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_login", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
