# Generated by Django 4.1.5 on 2023-01-20 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kiet", "0003_mymodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Mymodel",
        ),
        migrations.AddField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
